// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $calendar from "./routes/calendar.tsx";
import * as $events_id_ from "./routes/events/[id].tsx";
import * as $events_index from "./routes/events/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $host from "./routes/host.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $RSVPButton from "./islands/RSVPButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/calendar.tsx": $calendar,
    "./routes/events/[id].tsx": $events_id_,
    "./routes/events/index.tsx": $events_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/host.tsx": $host,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/RSVPButton.tsx": $RSVPButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
